-- AlterTable
ALTER TABLE `restaurant` ADD COLUMN `addOffer` VARCHAR(191) NULL,
    ADD COLUMN `closeTime` VARCHAR(191) NULL,
    ADD COLUMN `deliveryTime` INTEGER NULL,
    ADD COLUMN `openTime` VARCHAR(191) NULL,
    ADD COLUMN `rating` DOUBLE NULL DEFAULT 0;
